FROM ubuntu:20.04

RUN set -ex \
    # Setup environment
    && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -qq update \
    && apt-get -qq -y dist-upgrade \
    && apt-get -qq -y install --no-install-recommends \
        locales python3 python3-lxml python3-pip \
        # MegaSDK-REST dependencies
        libc-ares-dev libcrypto++-dev libcurl4-openssl-dev \
        libmagic-dev libsodium-dev libsqlite3-dev libssl-dev \
        # priiiiyo-mirror-bot dependencies
        aria2 curl ffmpeg jq p7zip-full mediainfo p7zip-rar pv \
    && sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen \
    && locale-gen \
    # Setup priiiiyo-mirror-bot dependencies
    && curl -fsSL https://github.com/P3TERX/aria2.conf/raw/master/dht.dat -O /usr/src/app/dht.dat && \
    && curl -fsSL https://github.com/P3TERX/aria2.conf/raw/master/dht6.dat -O /usr/src/app/dht6.dat \
    && curl -fsSL https://github.com/jaskaranSM/megasdkrest/releases/download/v0.1/megasdkrest -o /usr/local/bin/megasdkrest \
    && chmod +x /usr/local/bin/megasdkrest \
    && curl -fsSLO https://raw.githubusercontent.com/KenHV/Mirror-Bot/master/requirements.txt \
    && pip3 install --no-cache-dir -r requirements.txt \
    && rm requirements.txt \
    # Cleanup environment
    && apt-get -qq -y autoremove --purge \
    && apt-get -qq -y clean
    
ENV DEBIAN_FRONTEND=noninteractive \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

CMD ["bash", "start.sh"]
